# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-05 09:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0035_add_max_concurrent_submissions_allowed_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(default='Test Model', max_length=100)),
                ('predictions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Leaderboard')),
            ],
            options={
                'db_table': 'human_evaluation',
            },
        ),
    ]
