# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-06 03:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0036_humanevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanevaluation',
            name='predictions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'foo': 'bar'}),
        ),
    ]
